### ISSUE TITLE
Mask detection isnt working

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Face-Recognition-with-Mask-Jetson-Nano#1]
Hi buddy,

Awesome work, but I think mask detection isnt working at all. I tried with lots of different masks with 4 students in front of the cam  but its always showing "OFF".
I  think you might have forgotten to update/enable something in the github code.

**Comment by Qengineering** [comment]
I've wrongfully used `cv::Mat frame` as input for the mask detection. 
It should be of course `cv::Mat result_cnn` because the `Face[i].rect` refers to this input. 
See main.cpp line 372 `cv::Mat roi = result_cnn(RecClip);`

I've updated the Paddle-Lite deep learning model. Now it's up to date with the latest Paddle-Lite version, and you don't get any warnings any more.

I've modified the example movie Norton_M.mp4. Now there are three fragments with face masks.

Please note, PaddlePaddle has trained its face mask detection network only with white (or light blue) masks. Nowadays you see a lot of black masks or masks with fancy printing. Unfortunately, those will not be recognized by this network.
