### ISSUE TITLE
How to run with GPU

### ISSUE THREAD

**Issue by lbtanh** [Qengineering/Face-Recognition-with-Mask-Jetson-Nano#7]
Thanks for great repo, I wonder if we can run with GPU or both? Thanks again

**Comment by Qengineering** [comment]
Dear Ibtanh,

Thanks for your compliments.
You are using two frameworks here. 
Paddle-Lite which already uses CUDA (=GPU)
ncnn which uses not CUDA but Vulkan. As you know, Vulkan is also GPU based software used to accelerate matrix operations.

**Comment by lbtanh** [comment]
> Dear Ibtanh,
> 
> Thanks for your compliments.
> You are using two frameworks here.
> Paddle-Lite which already uses CUDA (=GPU)
> ncnn which uses not CUDA but Vulkan. As you know, Vulkan is also GPU based software used to accelerate matrix operations.

Dear @Qengineering, 

Thanks for quick reply, I have run the program successfully, but i dont see any GPU was used (monitor with jtop command). i'm just curious at that

**Comment by Qengineering** [comment]
When I run the app, jtop shows GPU usage, on and off. Up to 50%. In the main loop there's a lot of code not using the GPU, so no surprise when jtop samples the GPU it doesn't see a continue flux. However, running the movies, it must show something. Otherwise it may indicate a installation of ncnn / Paddle-Lite without Vulkan/CUDA on your Nano.
