### ISSUE TITLE
Face Recognition that wearing mask

### ISSUE THREAD

**Issue by MyraBaba** [Qengineering/Face-Recognition-with-Mask-Jetson-Nano#8]
Hi,

I really appreciate your work and great responsiveness of the issues.

Did you make any test that can we recognize people with mask ? I mean I have both phot in the DB bot maske and normal.

Can system recognize me with mask ? is there  any tested accuracy ? Or we need a new model to recognize people wearing mask

**Comment by Qengineering** [comment]
Dear @MyraBaba,

It is not possible the recognize people when they wearing a face mask. Or for that matter, dark sunglasses. You need to have at least five landmarks to get a reasonable accurate recognition. Missing two (the mouth corners and/or nose in case of a mask, or two eye locations) is too much to ask for the network. That's why we give a alarm in case of a mask.

**Comment by MyraBaba** [comment]
Hi,

I succeed  if I have two photos of the person one is masked one is normal in database like person#1.jpg and person#2.jpg.
Network successfully recognize the person in front of the camera with mask or without mask. 

Looks working.

**Comment by Qengineering** [comment]
Glad to hear!
Please let me know if you succeed with 100+ faces with mask. That would be really great.
