### ISSUE TITLE
How to Disable auto database fill ?

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Face-Recognition-with-Mask-Jetson-Nano#9]
How can I disable the auto database fill feature. 
If the face isnt found in the DB, I dont want to add it automatically.
How to do this ?

**Comment by Qengineering** [comment]
Main.cpp line 32, it's defined: `#define AUTO_FILL_DATABASE` Without a comment `//` in front of the line, it's ON.
Setting `//#define AUTO_FILL_DATABASE` will disable the auto fill. You need to recompile the code in order to make a modification take place. You ca also look in the code and follow the `AUTO_FILL_DATABASE` and change the directive `ifdef` for and regular `if` and use a variable of your choice.
